package supermarkt;
// Generated 10-nov-2014 12:06:39 by Hibernate Tools 3.2.1.GA



/**
 * Artikel generated by hbm2java
 */
public class Artikel  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private Float prijs;

    public Artikel() {
    }

    public Artikel(String naam, Float prijs) {
       this.naam = naam;
       this.prijs = prijs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Float getPrijs() {
        return this.prijs;
    }
    
    public void setPrijs(Float prijs) {
        this.prijs = prijs;
    }




}


